image: docker:stable

stages:
  - debug_docker
  - build_images
  - upload_images

debug_docker:
  stage: debug_docker
  script: docker info

build_httrack:
  interruptible: true
  stage: build_images
  script: docker build -t dkdde/jenkins-worker:httrack httrack

build_node-10_php-7.0_ruby-2.3:
  interruptible: true
  stage: build_images
  script: docker build -t dkdde/jenkins-worker:node-10_php-7.0_ruby-2.3 node-10_php-7.0_ruby-2.3

build_node-10_php-7.2_ruby-2.3:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-10_php-7.2_ruby-2.3 node-10_php-7.2_ruby-2.3

build_node-10_php-7.2_ruby-2.5:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-10_php-7.2_ruby-2.5 node-10_php-7.2_ruby-2.5

build_node-10_ruby-2.5:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-10_ruby-2.5 node-10_ruby-2.5

build_node-8_php-5.5_ruby-2.3:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-8_php-5.5_ruby-2.3 node-8_php-5.5_ruby-2.3

build_node-8_php-7.0_ruby-2.3:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-8_php-7.0_ruby-2.3 node-8_php-7.0_ruby-2.3

build_node-8_php-7.2_ruby-2.5:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-8_php-7.2_ruby-2.5 node-8_php-7.2_ruby-2.5

build_node-8_ruby-2.3:
  interruptible: true
  stage: build_imaged
  script: docker build -t dkdde/jenkins-worker:node-8_ruby-2.3 node-8_ruby-2.3

upload_images:
  interruptible: true
  stage: upload_images
  script: echo Here be dragons
