image: docker:stable
services:
  - docker:dind

stages:
  - build
  # - test
  # - release
  # - deploy

build:
  stage: build
  script:
    - docker build -t httrack httrack
    - docker build -t node-10_php-7.0_ruby-2.3 node-10_php-7.0_ruby-2.3
    - docker build -t node-10_php-7.2_ruby-2.3 node-10_php-7.2_ruby-2.3
    - docker build -t node-10_php-7.2_ruby-2.5 node-10_php-7.2_ruby-2.5
    - docker build -t node-10_ruby-2.5 node-10_ruby-2.5
    - docker build -t node-8_php-5.5_ruby-2.3 node-8_php-5.5_ruby-2.3
    - docker build -t node-8_php-7.0_ruby-2.3 node-8_php-7.0_ruby-2.3
    - docker build -t node-8_php-7.2_ruby-2.5 node-8_php-7.2_ruby-2.5
    - docker build -t node-8_ruby-2.3 node-8_ruby-2.3
