node-8_php-7.2_ruby-2.5:
  base_system: 'bionic-20180426'
  jdk_version: 8
  php: php7.2-cli
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-mbstring
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip
  ruby_version: 2.5
  nodejs_version: 8.10.0

node-8_php-7.0_ruby-2.3:
  base_system: 'xenial-20180417'
  jdk_version: 8
  php: php7.0-cli
  php_extensions:
    - php7.0-bcmath
    - php7.0-bz2
    - php7.0-curl
    - php7.0-dba
    - php7.0-dom
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-SimpleXML
    - php7.0-soap
    - php7.0-wddx
    - php7.0-xml
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-zip
  ruby_version: 2.3
  rubygems_version: 2.7.4
  bundler_version: 1.16.2
  nodejs_version: 8.10.0
  npm_version: 5.7.1

node-8_php-5.5_ruby-2.3:
  base_system: 'trusty-20180420'
  jdk_repo: 'ppa:openjdk-r/ppa'
  jdk_version: 8
  php: php5-cli
  php_extensions:
    - php5-common
    - php5-cli
    - php5-curl
  ruby_version: 2.3
  rubygems_version: 2.7.4
  bundler_version: 1.16.2
  nodejs_version: 8.10.0
  npm_version: 5.7.1

node-8_ruby-2.5:
  base_system: 'bionic-20180426'
  jdk_version: 8
  ruby_version: 2.5
  nodejs_version: 8.10.0
  npm_version: 5.7.1

node-8_ruby-2.3:
  base_system: 'xenial-20180417'
  jdk_version: 8
  ruby_version: 2.3
  rubygems_version: 2.7.4
  bundler_version: 1.16.2
  nodejs_version: 8.10.0
  npm_version: 5.7.1
