_image_defaults: &_image_defaults
  rake_version: 13.0.1
  rubygems_version: 3.1.2
  bundler_version: 2.1.4
  legacy_bundler_versions:
    - 2.0.2
    - 1.17.3
  npm_version: 6.13.6
  jdk_version: 8

_options:
  os:
    focal: &focal focal-20191129
    bionic: &bionic bionic-20191202
    xenial: &xenial xenial-20191212
    trusty: &trusty trusty
  nodejs:
    nodejs8_version: &nodejs8 8.17.0
    nodejs10_version: &nodejs10 10.18.1
    nodejs12_version: &nodejs12 12.14.1
  ruby:
    ruby23_version: &ruby23 2.3
    ruby25_version: &ruby25 2.5
    ruby27_version: &ruby27 2.7
  php:
    php5: &php5 php5-cli
    php70: &php70 php7.0-cli
    php72: &php72 php7.2-cli
    php74: &php74 php7.4-cli

node-10_php-7.4_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  php: *php74
  ruby_version: *ruby25
  php_ppa: 'ppa:ondrej/php'
  php_extensions:
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-curl
    - php7.4-dba
    - php7.4-dom
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-SimpleXML
    - php7.4-soap
    - php7.4-xml
    - php7.4-xmlreader
    - php7.4-xmlwriter
    - php7.4-zip

node-12_php-7.4_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs12
  php: *php74
  ruby_version: *ruby25
  php_ppa: 'ppa:ondrej/php'
  php_extensions:
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-curl
    - php7.4-dba
    - php7.4-dom
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-SimpleXML
    - php7.4-soap
    - php7.4-xml
    - php7.4-xmlreader
    - php7.4-xmlwriter
    - php7.4-zip

node-10_php-7.2_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  php: *php72
  ruby_version: *ruby25
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip

node-8_php-7.2_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs8
  php: *php72
  ruby_version: *ruby25
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip

node-10_php-7.2_ruby-2.3:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  php: *php72
  ruby_version: *ruby23
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip

node-10_php-7.0_ruby-2.3:
  base_system: *xenial
  <<: *_image_defaults
  nodejs_version: *nodejs10
  ruby_version: *ruby23
  php: *php70
  php_extensions:
    - php7.0-bcmath
    - php7.0-bz2
    - php7.0-curl
    - php7.0-dba
    - php7.0-dom
    - php7.0-gd
    - php7.0-intl
    - php7.0-mbstring
    - php7.0-SimpleXML
    - php7.0-soap
    - php7.0-wddx
    - php7.0-xml
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-zip

node-8_php-7.0_ruby-2.3:
  base_system: *xenial
  <<: *_image_defaults
  nodejs_version: *nodejs8
  php: *php70
  ruby_version: *ruby23
  php_extensions:
    - php7.0-bcmath
    - php7.0-bz2
    - php7.0-curl
    - php7.0-dba
    - php7.0-dom
    - php7.0-gd
    - php7.0-intl
    - php7.0-mbstring
    - php7.0-SimpleXML
    - php7.0-soap
    - php7.0-wddx
    - php7.0-xml
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-zip

node-8_php-5.5_ruby-2.3:
  base_system: *trusty
  <<: *_image_defaults
  nodejs_version: *nodejs8
  php: *php5
  ruby_version: *ruby23
  jdk_ppa: 'ppa:openjdk-r/ppa'
  php_extensions:
    - php5-common
    - php5-cli
    - php5-curl

node-10_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  ruby_version: *ruby25

node-8_ruby-2.3:
  base_system: *xenial
  <<: *_image_defaults
  nodejs_version: *nodejs8
  ruby_version: *ruby23
  