_image_defaults: &_image_defaults
  rake_version: 13.0.0
  rubygems_version: 3.0.6
  bundler_version: 2.0.2
  npm_version: 6.11.3
  jdk_version: 8

_options:
  os:
    bionic: &bionic bionic-20190912.1
    xenial: &xenial xenial-20190904
    trusty: &trusty trusty
  nodejs:
    nodejs8_version: &nodejs8 8.16.1
    nodejs10_version: &nodejs10 10.16.3
  ruby:
    ruby23_version: &ruby23 2.3
    ruby25_version: &ruby25 2.5
  php:
    php5: &php5 php5-cli
    php70: &php70 php7.0-cli
    php72: &php72 php7.2-cli

node-10_php-7.2_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  php: *php72
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip
  ruby_version: *ruby25
  nodejs_version: *nodejs10

node-8_php-7.2_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  php: *php72
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip
  ruby_version: *ruby25
  nodejs_version: *nodejs8

node-10_php-7.2_ruby-2.3:
  base_system: *bionic
  <<: *_image_defaults
  php: *php72
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip
  ruby_version: *ruby23
  nodejs_version: *nodejs10

node-10_php-7.0_ruby-2.3:
  base_system: *xenial
  <<: *_image_defaults
  php: *php70
  php_extensions:
    - php7.0-bcmath
    - php7.0-bz2
    - php7.0-curl
    - php7.0-dba
    - php7.0-dom
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-SimpleXML
    - php7.0-soap
    - php7.0-wddx
    - php7.0-xml
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-zip
  ruby_version: *ruby23
  nodejs_version: *nodejs10

node-8_php-7.0_ruby-2.3:
  base_system: *xenial
  <<: *_image_defaults
  php: *php70
  php_extensions:
    - php7.0-bcmath
    - php7.0-bz2
    - php7.0-curl
    - php7.0-dba
    - php7.0-dom
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-SimpleXML
    - php7.0-soap
    - php7.0-wddx
    - php7.0-xml
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-zip
  ruby_version: *ruby23
  nodejs_version: *nodejs8

node-8_php-5.5_ruby-2.3:
  base_system: *trusty
  <<: *_image_defaults
  jdk_repo: 'ppa:openjdk-r/ppa'
  php: *php5
  php_extensions:
    - php5-common
    - php5-cli
    - php5-curl
  ruby_version: *ruby23
  nodejs_version: *nodejs8

node-10_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  ruby_version: *ruby25
  nodejs_version: *nodejs10

node-8_ruby-2.3:
  <<: *_image_defaults
  base_system: *xenial
  ruby_version: *ruby23
  nodejs_version: *nodejs8
