_default: &_default
  rake_version: 12.3.1
  rubygems_version: 2.7.7
  bundler_version: 1.16.6
  nodejs_version: 8.12.0
  npm_version: 6.4.1

_bionic: &_bionic bionic-20180821
_xenial: &_xenial xenial-20180808
_trusty: &_trusty trusty-20180807

node-8_php-7.2_ruby-2.5:
  <<: *_default
  base_system: *_bionic
  jdk_version: 8
  php: php7.2-cli
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-mbstring
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip
  ruby_version: 2.5

node-8_php-7.0_ruby-2.3:
  <<: *_default
  base_system: *_xenial
  jdk_version: 8
  php: php7.0-cli
  php_extensions:
    - php7.0-bcmath
    - php7.0-bz2
    - php7.0-curl
    - php7.0-dba
    - php7.0-dom
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-SimpleXML
    - php7.0-soap
    - php7.0-wddx
    - php7.0-xml
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-zip
  ruby_version: 2.3

node-8_php-5.5_ruby-2.3:
  <<: *_default
  base_system: *_trusty
  jdk_repo: 'ppa:openjdk-r/ppa'
  jdk_version: 8
  php: php5-cli
  php_extensions:
    - php5-common
    - php5-cli
    - php5-curl
  ruby_version: 2.3

node-8_ruby-2.5:
  <<: *_default
  base_system: *_bionic
  jdk_version: 8
  ruby_version: 2.5

node-8_ruby-2.3:
  <<: *_default
  base_system: *_xenial
  jdk_version: 8
  ruby_version: 2.3
