_image_defaults: &_image_defaults
  composer_version: 1.10.9
  rake_version: 13.0.1
  rubygems_version: 3.1.4
  bundler_version: 2.1.4
  legacy_bundler_versions:
    - 1.17.3
    - 2.0.2
  npm_version: 6.14.7
  jdk_version: 8

_options:
  os:
    bionic: &bionic ubuntu:bionic-20200630
    focal: &focal ubuntu:focal-20200703
  nodejs:
    nodejs10_version: &nodejs10 10.22.0
    nodejs12_version: &nodejs12 12.18.3
  ruby:
    ruby23_version: &ruby23 2.3
    ruby25_version: &ruby25 2.5
    ruby27_version: &ruby27 2.7
  php:
    php5: &php5 php5-cli
    php70: &php70 php7.0-cli
    php72: &php72 php7.2-cli
    php74: &php74 php7.4-cli

node-12_php-7.4_ruby-2.7:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs12
  php: *php74
  ruby_version: *ruby27
  ruby_ppa: 'ppa:brightbox/ruby-ng'
  php_ppa: 'ppa:ondrej/php'
  php_extensions:
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-curl
    - php7.4-dba
    - php7.4-dom
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-SimpleXML
    - php7.4-soap
    - php7.4-xml
    - php7.4-xmlreader
    - php7.4-xmlwriter
    - php7.4-zip
  additional_apt_packages:
    - chromium-browser
    - chromium-browser-l10n
    - libmariadb-dev

node-10_php-7.4_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  php: *php74
  ruby_version: *ruby25
  ruby_ppa: 'ppa:brightbox/ruby-ng'
  php_ppa: 'ppa:ondrej/php'
  php_extensions:
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-curl
    - php7.4-dba
    - php7.4-dom
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-SimpleXML
    - php7.4-soap
    - php7.4-xml
    - php7.4-xmlreader
    - php7.4-xmlwriter
    - php7.4-zip
  additional_apt_packages:
    - chromium-browser
    - chromium-browser-l10n
    - libmysqlclient-dev

node-12_php-7.4_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs12
  php: *php74
  ruby_version: *ruby25
  php_ppa: 'ppa:ondrej/php'
  ruby_ppa: 'ppa:brightbox/ruby-ng'
  php_extensions:
    - php7.4-bcmath
    - php7.4-bz2
    - php7.4-curl
    - php7.4-dba
    - php7.4-dom
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-SimpleXML
    - php7.4-soap
    - php7.4-xml
    - php7.4-xmlreader
    - php7.4-xmlwriter
    - php7.4-zip
  additional_apt_packages:
    - chromium-browser
    - chromium-browser-l10n
    - libmysqlclient-dev

node-10_php-7.2_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  php: *php72
  ruby_version: *ruby25
  ruby_ppa: 'ppa:brightbox/ruby-ng'
  php_extensions:
    - php7.2-bcmath
    - php7.2-bz2
    - php7.2-curl
    - php7.2-dba
    - php7.2-dom
    - php7.2-gd
    - php7.2-intl
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-SimpleXML
    - php7.2-soap
    - php7.2-wddx
    - php7.2-xml
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-zip
  additional_apt_packages:
    - chromium-browser
    - chromium-browser-l10n
    - libmysqlclient-dev

node-12_ruby-2.7:
  base_system: *bionic
  <<: *_image_defaults
  ruby_version: *ruby27
  ruby_ppa: 'ppa:brightbox/ruby-ng'
  nodejs_version: *nodejs12
  additional_apt_packages:
    - libmariadb-dev

node-10_ruby-2.5:
  base_system: *bionic
  <<: *_image_defaults
  nodejs_version: *nodejs10
  ruby_version: *ruby25
  ruby_ppa: 'ppa:brightbox/ruby-ng'
  additional_apt_packages:
    - chromium-browser
    - chromium-browser-l10n
    - libmysqlclient-dev
