FROM ubuntu:<%= @data['system'] %>

LABEL maintainer.first="Nicolai Reuschling 'nicolai.reuschling@dkd.de'" \
      maintainer.second="Michael Skrynski 'michael.skrynski@dkd.de'"

# Add locales after locale-gen as needed
# Upgrade packages on image
# Preparations for sshd
# RUN locale-gen de_DE.UTF-8 &&\
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q upgrade -y -o Dpkg::Options::="--force-confnew" --no-install-recommends &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      curl \
      libxslt-dev \
      libxml2-dev \
      libmysqlclient-dev \
      build-essential \
      sqlite3 \
      libsqlite3-dev \
      libcurl4-openssl-dev \
      imagemagick \
      libmagickwand-dev \
      # language-pack-de-base \
      openssh-server &&\
    mkdir -p /var/run/sshd

# Setting language
# ENV LANG de_DE.UTF-8
# ENV LANGUAGE de_DE:de
# ENV LC_ALL de_DE.UTF-8

# Install JDK <%= @data['jdk'] %> (latest edition)
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends openjdk-<%= @data['jdk'] %>-jre-headless

<% if @data['php'] %>
# Install PHP <%= @data['php'] %> (latest version)
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends php<%= @data['php'] %>
      <% if @data['php_extensions'] %>
        <% @data['php_extensions'].each do |extension| %>
          php<%= @data['php'] %>-<%= extension %>
        <% end %>
      <% end %>
<% end %>

# Install Ruby <%= @data['ruby'] %> (latest version)
<% if @data['ruby_repo'] %>
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends apt-transport-https ca-certificates software-properties-common &&\
    add-apt-repository ppa:brightbox/ruby-ng &&\
    apt-get update -q &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      ruby<%= @data['ruby'] %> \
      ruby<%= @data['ruby'] %>-dev \
      nodejs \
      npm
<% else %>
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      ruby<%= @data['ruby'] %> \
      ruby<%= @data['ruby'] %>-dev \
      nodejs \
      npm
<% end %>

# Add user jenkins to the image
RUN useradd -m -d /home/jenkins -s /bin/sh jenkins
<% if @data['debug'] %>
RUN mkdir /home/jenkins/.ssh
ADD sshd/jenkins_worker.pub /home/jenkins/.ssh/authorized_keys
RUN chown -R jenkins:jenkins /home/jenkins/.ssh &&\
    chmod -R 0700 /home/jenkins/.ssh
<% end %>

# Cleanup
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q autoremove &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q clean -y &&\
    rm -rf /var/lib/apt/lists/* &&\
    rm -f /var/cache/apt/*.bin

# Modify SSHD config
ADD sshd/sshd_config /etc/ssh/sshd_config

# Standard SSH port
EXPOSE 22

# Mount volumes
VOLUME ["/home/jenkins/.ssh", "/home/jenkins/composer", "/home/jenkins/ruby"]

# Default command
<% if @data['debug'] %>
CMD ["/usr/sbin/sshd", "-D", "-E", "/var/log/security"]
<% else %>
CMD ["/usr/sbin/sshd", "-D"]
<% end %>
