# <%= "#{dockerhub_organisation}/#{container_name}:#{container_tag}" %>
FROM ubuntu:<%= base_system %>

LABEL maintainer.first="Nicolai Reuschling 'nicolai.reuschling@dkd.de'"

# Setup environment
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Add user jenkins
RUN useradd -m -d /home/jenkins -s /bin/sh jenkins

# Setup locale
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q upgrade -y -o Dpkg::Options::="--force-confnew" --no-install-recommends &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends locales &&\
    locale-gen en_US.UTF-8 de_DE.UTF-8 && localedef -i en_US -f UTF-8 en_US.UTF-8

# let's skip this for testing purposes: DEBIAN_FRONTEND="noninteractive" apt-get -q upgrade -y -o Dpkg::Options::="--force-confnew" --no-install-recommends &&\
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      openssh-client \
      wget \
      curl \
      unzip \
      locales \
      libxslt-dev \
      libxml2-dev \
      libmysqlclient-dev \
      build-essential \
      sqlite3 \
      libsqlite3-dev \
      libcurl4-openssl-dev \
      imagemagick \
      libmagickwand-dev \
      net-tools

# Install Git
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      apt-transport-https \
      ca-certificates \
      software-properties-common &&\
    add-apt-repository ppa:git-core/ppa &&\
    apt-get update -q

RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends git

# Create local cache directories
RUN mkdir -p {/home/jenkins/.ssh,/home/jenkins/composer-cache,/home/jenkins/.npm,/home/jenkins/bundler-cache} &&\
    chown -R jenkins:jenkins {/home/jenkins/.ssh,/home/jenkins/composer-cache,/home/jenkins/.npm,/home/jenkins/bundler-cache} &&\
    chmod -R 0700 {/home/jenkins/.ssh,/home/jenkins/composer-cache,/home/jenkins/.npm,/home/jenkins/bundler-cache}

<% if defined?(jdk_repo) %>
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      apt-transport-https \
      ca-certificates \
      software-properties-common &&\
    DEBIAN_FRONTEND="noninteractive" add-apt-repository <%= jdk_repo %> &&\
    DEBIAN_FRONTEND="noninteractive" apt-get update -q
<% end %>

# Install JDK (v<%= jdk_version %>)
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      openjdk-<%= jdk_version %>-jre-headless

<% if defined?(php) %>
# Install PHP (<%= php %>)
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends <%= php %> \
  <% if defined?(php_extensions) %>
    <%= php_extensions.join(' ') %>
  <% end %>
<% end %>

<% if defined?(ruby_version) %>
# Install Ruby (v<%= ruby_version %>)
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      apt-transport-https \
      ca-certificates \
      software-properties-common &&\
    add-apt-repository ppa:brightbox/ruby-ng &&\
    apt-get update -q

RUN DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
      ruby<%= ruby_version %> \
      ruby<%= ruby_version %>-dev

<% if defined?(rake_version) && defined?(rubygems_version) && defined?(bundler_version) %>
# Install Rake, update RubyGems and install Bundler
RUN gem install rake --version=<%= rake_version %> --no-doc --no-post-install-message &&\
    gem update --system <%= rubygems_version %> --no-doc --no-post-install-message &&\
    gem install bundler --version=<%= bundler_version %> --no-doc --no-post-install-message
<% end %>
<% end %>

<% if defined?(nodejs_version) %>
# Install NodeJS (v<%= nodejs_version %>)
RUN curl -SLO "https://nodejs.org/dist/v<%= nodejs_version %>/node-v<%= nodejs_version %>-linux-x64.tar.xz" &&\
    tar -xJf "node-v<%= nodejs_version %>-linux-x64.tar.xz" -C /usr/local --strip-components=1 &&\
    ln -s /usr/local/bin/node /usr/local/bin/nodejs &&\
    rm /node-v<%= nodejs_version %>-linux-x64.tar.xz

<% if defined?(npm_version) %>
# Install npm (v<%= npm_version %>)
RUN npm install -g npm@<%= npm_version %>
<% end %>
<% end %>

# Cleanup
RUN DEBIAN_FRONTEND="noninteractive" apt-get -q autoremove &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q clean -y &&\
    rm -rf /var/lib/apt/lists/* &&\
    rm -f /var/cache/apt/*.bin
